FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    curl \
    file \
    patchelf \
    libfuse2 \
    binutils \
    pkg-config \
    \
    qt6-base-dev \
    qt6-base-dev-tools \
    qmake6 \
    qt6-multimedia-dev \
    libqt6serialport6-dev \
    \
    libgl1-mesa-dev \
    \
    libhidapi-dev \
    libusb-1.0-0-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src